package com.waynejo.parser.element

case class AndParsingElement1[A, B](pe0: ParsingElement[A], reducer: ((A)) => B, debugString: String = "") extends ParsingElement[B]
case class AndParsingElement2[A, B, C](pe0: ParsingElement[A], pe1: ParsingElement[B], reducer: ((A, B)) => C, debugString: String = "") extends ParsingElement[C]
case class AndParsingElement3[A, B, C, D](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], reducer: ((A, B, C)) => D, debugString: String = "") extends ParsingElement[D]
case class AndParsingElement4[A, B, C, D, E](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], reducer: ((A, B, C, D)) => E, debugString: String = "") extends ParsingElement[E]
case class AndParsingElement5[A, B, C, D, E, F](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], reducer: ((A, B, C, D, E)) => F, debugString: String = "") extends ParsingElement[F]
case class AndParsingElement6[A, B, C, D, E, F, G](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], pe5: ParsingElement[F], reducer: ((A, B, C, D, E, F)) => G, debugString: String = "") extends ParsingElement[G]
case class AndParsingElement7[A, B, C, D, E, F, G, H](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], pe5: ParsingElement[F], pe6: ParsingElement[G], reducer: ((A, B, C, D, E, F, G)) => H, debugString: String = "") extends ParsingElement[H]
case class AndParsingElement8[A, B, C, D, E, F, G, H, I](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], pe5: ParsingElement[F], pe6: ParsingElement[G], pe7: ParsingElement[H], reducer: ((A, B, C, D, E, F, G, H)) => I, debugString: String = "") extends ParsingElement[I]
case class AndParsingElement9[A, B, C, D, E, F, G, H, I, J](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], pe5: ParsingElement[F], pe6: ParsingElement[G], pe7: ParsingElement[H], pe8: ParsingElement[I], reducer: ((A, B, C, D, E, F, G, H, I)) => J, debugString: String = "") extends ParsingElement[J]
case class AndParsingElement10[A, B, C, D, E, F, G, H, I, J, K](pe0: ParsingElement[A], pe1: ParsingElement[B], pe2: ParsingElement[C], pe3: ParsingElement[D], pe4: ParsingElement[E], pe5: ParsingElement[F], pe6: ParsingElement[G], pe7: ParsingElement[H], pe8: ParsingElement[I], pe9: ParsingElement[J], reducer: ((A, B, C, D, E, F, G, H, I, J)) => K, debugString: String = "") extends ParsingElement[K]
